### ISSUE TITLE
seems that it does not work. panic: runtime error: index out of range [1] with length 1

### ISSUE THREAD

**Issue by cnscorpions** [iochen/skillshare-dl#8]
Hi, thank for your work.

After following your instruction there, it thrown an error as below:
```
root@downloader:/home/videos# skillshare-dl -cookie cookie.txt -id 442860604
Video ID List: [442860604]
=========== Downloading 0 ===========
panic: runtime error: index out of range [1] with length 1

goroutine 21 [running]:
github.com/iochen/skillshare-dl.(*Session).Video(0xc000030fb0, 0x7e663a, 0xd, 0x7f9de7, 0x90, 0x0, 0x0, 0x0, 0x0, 0x0)        /home/runner/work/skillshare-dl/skillshare-dl/session.go:36 +0x82d
main.Download.func1(0xc00015e6a0, 0xc000019380, 0x38, 0x4, 0x2e15c4, 0x1a65843c, 0xc0001e5b80, 0x1b, 0x0, 0x0)
        /home/runner/work/skillshare-dl/skillshare-dl/cmd/skillshare-dl/main.go:76 +0xa1
created by main.Download
        /home/runner/work/skillshare-dl/skillshare-dl/cmd/skillshare-dl/main.go:74 +0x266
root@downloader:/home/videos#
```

I know nothing about Golang.

Any help will be highly appreciated.

**Comment by mahdisky** [comment]
i have this error too
